In [1]:
pip install otter-grader
pip install datascience

SyntaxError: invalid syntax (567109104.py, line 1)

In [1]:
import otter
import numpy as np
%matplotlib inline
import otter
import matplotlib.pylab as plt
grader = otter.Notebook()


1. Creando arreglos

En clase, contamos el número de veces que caracteres aparecen en cada capítulo del libro clásico [*Little Women*](https://inferentialthinking.com/chapters/01/3/1/Literary_Characters.html?highlight=little%20women).  En ciencias computacionales, la palabra "caracter" también hace referencia a una letra, dígito, espacio o signo de puntuación; cada elemento de un texto. El siguiente código genera una gráfica de dispersión en la cual cada punto corresponde a un capítulo de *Little Women*. La posición horizontal de un punto mide el número de puntos en un capítulo. La posición vertical midel el número total de caracteres.

In [2]:
# Ejecute esta celda para configurar su notebook, pero por favor no la cambie.

import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

**Pregunta 1.** Cree un arreglo llamado `numeros_extraños` que contenga los siguientes números (en el orden dado) **(4 Points)**:

1. -2
2. El piso (floor) de 17.6
3. 3
4. 5 a la potencia del techo (ceil) de 5.3

*Hint:* `floor` y `ceil` son funciones en el módulo `math`. Importar módulos se trabaja en el Lab 2.

*Nota:* Las listas de Python son y se comportan diferente de los arreglos de NumPy. En este curso usaremos arreglos de NumPy, así que cuando haga un **arreglo**, no haga una lista de Python.

In [4]:
import math

In [7]:
# BEGIN SOLUTION NO PROMPT
numeros_extraños = np.array((-2,math.floor(17.6), 3, math.ceil(5.3)))
# END SOLUTION
""" # BEGIN PROMPT
numeros_extraños = ...
""" # END PROMPT
numeros_extraños

array([-2, 17,  3,  6])

In [17]:
isinstance(numeros_extraños, np.ndarray)

True

In [18]:
numeros_extraños[0] == -2

True

In [19]:
numeros_extraños[1] == 17

True

In [20]:
numeros_extraños[2] == 3

True

In [22]:
numeros_extraños[3] == 6

True

**Pregunta 2.** Cree un arreglo llamado `titulo_libros` que contenga las tres siguientes cadenas de caracteres: "Eats", "Shoots", and "and Leaves". **(4 Puntos)**

In [24]:
# BEGIN SOLUTION NO PROMPT
titulo_libros = np.array(('Eats', 'Shoots', 'and Leaves'))
# END SOLUTION
""" # BEGIN PROMPT
titulo_libros = ...
""" # END PROMPT
titulo_libros

array(['Eats', 'Shoots', 'and Leaves'],
      dtype='<U10')

In [25]:
isinstance(titulo_libros, np.ndarray)

True

In [27]:
titulo_libros.dtype == '<U10'

True

In [19]:
titulo_libros[0] == 'Eats'

True

In [28]:
titulo_libros[1] == 'Shoots'

True

In [29]:
titulo_libros[2] == 'and Leaves'

True

Las cadenas de caracteres (strings) tienen un método llamado `join`. `join` toma como argumento un arreglo de cadenas de caracteres y regresa una cadena de caracteres. Específicamente, el resultado es una sola cadena de caracteres, que es la [concatenación](https://es.wikipedia.org/wiki/Concatenaci%C3%B3n) ("juntar") todas las cadenas de caracteres en el arreglo.


**Pregunta 3.** Use el arreglo `titulo_libros` y el método `join` para crear dos arreglos **(4 Puntos)**:

1. "Eats, Shoots, and Leaves" (llámelo `usando_comas`)
2. "Eats Shoots and Leaves" (llámelo `sin_comas`)


In [31]:
# BEGIN SOLUTION NO PROMPT
usando_comas = np.array(("Eats, Shoots, and Leaves" ))
sin_comas = np.array(("Eats Shoots and Leaves"))

# END SOLUTION
""" # BEGIN PROMPT
usando_comas = ...
sin_comas = ...
""" # END PROMPT
print('usando_comas:', usando_comas)
print('sin_comas:', sin_comas)

usando_comas: Eats, Shoots, and Leaves
sin_comas: Eats Shoots and Leaves


In [32]:
isinstance(usando_comas, np.ndarray) and isinstance(sin_comas, np.ndarray)

True

In [38]:
usando_comas == 'Eats, Shoots, and Leaves'

array(True, dtype=bool)

In [39]:
sin_comas == "Eats Shoots and Leaves"

array(True, dtype=bool)

## Indexando arreglos

Estos ejercicios están pensados en dar práctica al momento de acceder a elementos individuales de los arreglos. En Python (y en muchos lenguajes de programación), cada elemento es accesible mediante su  *índice*; por ejemplo, el primer elmento es el elemento con índice 0. Los índices deben ser números **enteros**.


***Nota:* Si usted tiene experiencia previa programando, la notación de corchetes le debe ser familiar. NO use la notación de corchetes cuando esté indexando (i.e. `arr[0]`), pues esto puede conducir a un tipo de dato diferente del que estamos esperando. Le puede además hacer fallar en la revisión.**

En caso de sentirse atascado, revise la [Referencia de Python](http://data8.org/fa23/reference/)


**Pregunta 1.** La siguiente celda crea un arreglo de algunos números. Asigne `tercer_elemento`  al tercer elemento de `algunos_numeros`. **(4 Puntos)**

In [40]:
algunos_numeros = make_array(-1, -3, -6, -10, -15)

In [41]:
# BEGIN SOLUTION NO PROMPT
tercer_elemento = -6
# END SOLUTION
""" # BEGIN PROMPT
tercer_elemento = ...
""" # END PROMPT
tercer_elemento

-6

In [43]:
tercer_elemento == -6 or tercer_elemento == -6.0

True

In [44]:
type(tercer_elemento) == int or type(tercer_elemento) == float

True

**Pregunta 2.** La próxima celda crea una tabla que muestra información sobre los elementos de `algunos_numeros` y su orden. Corra la celda para ver la tabla parcialmente completa y llene la información faltante (las celdas que dicen "Ellipsis") mediante la asignación `espacio_a`, `espacio_b`, `espacio_c`, y `espacio_d` para corregir los elementos en la tabla. **(4 Puntos)**

*Hint* Reemplace los `...` con cadenas de caracteres o números. Recuerde que los índices deben ser **enteros**.

In [45]:
# BEGIN SOLUTION NO PROMPT
espacio_a = "tercero"
espacio_b = "cuarto"
espacio_c = 0
espacio_d = 3
elementos_de_algunos_numeros = Table().with_columns(
    "Nombre de la posicion", make_array("primero", "segundo", espacio_a, espacio_b, "quinto"),
    "Idice",                     make_array(espacio_c, 1, 2, espacio_d, 4),
    "Elemento",                   algunos_numeros)
# END SOLUTION

""" # BEGIN PROMPT
espacio_a = ...
espacio_b = ...
espacio_c = ...
espacio_d = ...
elementos_de_algunos_numeros = Table().with_columns(
    "Nombre de la posicion", make_array("primero", "segundo", espacio_a, espacio_b, "quinto"),
    "Idice",                     make_array(espacio_c, 1, 2, espacio_d, 4),
    "Elemento",                   algunos_numeros)

""" # END PROMPT
elementos_de_algunos_numeros

Nombre de la posicion,Idice,Elemento
primero,0,-1
segundo,1,-3
tercero,2,-6
cuarto,3,-10
quinto,4,-15


In [47]:
isinstance(elementos_de_algunos_numeros, Table)

True

In [30]:
espacio_a == "tercero" and espacio_b == "cuarto" and espacio_c == 0 and espacio_d == 3

True

**Pregunta 3.** En ocasiones usted querrá encontrar el **último** elemento de un arreglo. Suponga que el arreglo tiene 142 elementos. ¿Cuál es el índice del último elemento? **(4 Puntos)**

*Nota:* Su respuesta deberá ser un número positivo.


In [48]:
# BEGIN SOLUTION NO PROMPT
indice_ultimo_elemento = 141

""" # BEGIN PROMPT
indice_ultimo_elemento = ...

""" # END PROMPT
indice_ultimo_elemento

141

In [49]:
indice_ultimo_elemento == 141 

True

In [50]:
type(indice_ultimo_elemento) == int

True

Con frecuencia, usted no conocerá el número de elementos de un arreglo, su *longitud*. (Por ejemplo, puede ser un conjunto de datos que usted encuentra en Internet.) La función `len` toma un solo argumento, un arreglo, y entrega un número entero que representa la longitud o tamaño de dicho arreglo.

**Pregunta 4.** La siguiente celda carga un arreglo llamado `año_nacimiento_presidentes`. Llamando `tabla.column(...)` en una tabla entrega un arreglo con la columna especificada, en este caso la columna `Año de nacimiento` de la tabla `nacimiento_presidentes`. El último elemento en ese arreglo es el más reciente entre los años de nacimiento entre todos los ex-presidentes de los Estados Unidos. Asigne ese año a `año_nacimiento_mas_reciente` **(4 Puntos)**


**Nota:** Evite googlear la respuesta. Usted debería ser capaz de responder esta pregunta únicamente usando métodos de tablas.


In [51]:
# BEGIN SOLUTION NO PROMPT
año_nacimiento_presidentes = Table.read_table("president_births.csv").column('Birth Year')  #Modificar una vez se ajuste la tabla.
most_recent_birth_year = año_nacimiento_presidentes[-1]

""" # BEGIN PROMPT
most_recent_birth_year = ...

""" # END PROMPT
most_recent_birth_year

1917

In [57]:
most_recent_birth_year == 1917

True

## Artimética básica de arreglos

**Pregunta 1.** Multiplique los números 42, -4224, 424224242, y 250 por 157. Asigne cada variable en la siguiente celda de tal forma que  `primer_producto` se asigne al resultado de $42 * 157$, `segundo_producto` al resultado de $-4224 * 157$ y así sucesivamente. **(4 Puntos)**

*Nota*: Para esta pregunta, **no** use arreglos.

In [2]:
# BEGIN SOLUTION NO PROMPT
primer_producto = 42 * 157
segundo_producto =  -4224 * 157
tercer_producto = 424224242 * 157
cuarto_producto = 250 * 157

""" # BEGIN PROMPT
primer_producto = ...
segundo_producto = ...
tercer_producto = ...
cuarto_producto = ...

""" # END PROMPT
print("Primer Producto:", primer_producto)
print("Segundo Producto:", segundo_producto)
print("Tercer Producto:", tercer_producto)
print("Cuarto Producto:", cuarto_producto)

Primer Producto: 6594
Segundo Producto: -663168
Tercer Producto: 66603205994
Cuarto Producto: 39250


In [3]:
primer_producto == 6594 and segundo_producto == -663168 and tercer_producto == 66603205994 and cuarto_producto == 39250

True

In [6]:
type(primer_producto) == int and type(segundo_producto) == int and type(tercer_producto) == int and type(cuarto_producto) == int

True

**Pregunta 2.** Ahora, haga los mismos cálculos, pero esta vez usando un arreglo llamado `numeros`y un solo operador de multiplicación (`*`). Almacene los 4 resultados en un arreglo llamado `productos`. **(4 Puntos)**

In [9]:
# BEGIN SOLUTION NO PROMPT
numeros = np.array([42,-4224,424224242,250])
productos = numeros * 157
""" # BEGIN PROMPT
numeros = ...
productos = ...
""" # END PROMPT
productos

array([       6594,     -663168, 66603205994,       39250])

In [10]:
len(productos) == 4

True

In [11]:
productos[0] == 6594 and productos[1] == -663168 and productos[2] == 66603205994 and productos[3] == 39250

True

**Pregunta 3.** Ups, cometimos un error. En lugar de 157, queremos que multiplique cada número por 1577. Calcule los productos correctos en la celda de abajo usando aritmética de arreglos. Note que su trabajo es realmente sencillo si previamente definió un arreglo que contiene los 4 números. **(4 Puntos)**

In [12]:
# BEGIN SOLUTION NO PROMPT
productos_correctos = numeros * 1577

""" # BEGIN PROMPT
productos_correctos = ...

""" # END PROMPT
productos_correctos

array([       66234,     -6661248, 669001629634,       394250])

In [13]:
len(productos_correctos) == 4

True

In [16]:
productos_correctos[0] == 66234 and productos_correctos[1] == -6661248 and productos_correctos[2] == 669001629634 and productos_correctos[3] == 394250

True

Estudiando a los sobrevivientes

**Pregunta 4.** Hemos cargado un arreglo de temperaturas en la siguiente celda. Cada número es la temperatura más alta registrada en un día en una estación de medición del clima. Al ser datos de la agencia gubernamental de Estados Unidos [NOAA](https://www.noaa.gov/), todas las temperaturas están en Fahrenheit.

Convierta todas las temperaturas a Celsius, primero sustrayendo 32 de ellas. Luego, multiplique los resultados por by $\frac{5}{9}$, i.e. $C = (F - 32) * \frac{5}{9}$. Luego de convertir las temperaturas a Celsius, asegúrese de **REDONDEAR** el resultado final al entero más cercano usando la función `np.round`. **(4 Puntos)**

In [27]:
max_temps = Table.read_table("temperatures.csv").column("Daily Max Temperature") #Modificar una vez se ajuste la tabla.

In [20]:
# BEGIN SOLUTION NO PROMPT
celsius_max_temps = (max_temps - 32) * (5/9)
celsius_temps_redondeadas = np.round(celsius_max_temps)

""" # BEGIN PROMPT
celsius_max_temps = ...
celsius_temps_redondeadas = ...

""" # END PROMPT
celsius_temps_redondeadas

array([ -4.,  31.,  32., ...,  17.,  23.,  16.])

In [30]:
isinstance(celsius_temps_redondeadas, np.ndarray)

True

In [22]:
len(celsius_temps_redondeadas) == 65000

True

In [26]:
celsius_temps_redondeadas.dtype == 'float64'

True

**Pregunta 5.** La celda de abajo carga todas las más *bajas* temperaturas de cada día (en Fahrenheit). Calcule el intervalo diario de temperaturas de cada día. Esto es, calcule la diferencia, por día, entre las respectivas temperaturas máxima y mínima. **¡Preste atención a las unidades y de su respuesta en Celsius!** Asegúrese de **NO** redondear su respuesta.


*Hint:* Use `min_temps` y/o `max_temps`, y preste atención a la conversión de unidades. Escriba el cálculo matemático a mano si no logra avanzar.

In [28]:
min_temps = Table.read_table("temperatures.csv").column("Daily Min Temperature")

In [29]:
# BEGIN SOLUTION NO PROMPT
celsius_min_temps = (min_temps - 32) * (5/9)
celsius_temps_rangos = celsius_max_temps - celsius_min_temps

""" # BEGIN PROMPT
celsius_temps_rangos = ...

""" # END PROMPT
celsius_temps_rangos

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

In [31]:
isinstance(celsius_temps_rangos, np.ndarray)

True

In [32]:
celsius_temps_rangos.dtype == 'float64'

True

In [37]:
celsius_temps_rangos[0] == 6.6666666666666661 and celsius_temps_rangos[-1] == 11.111111111111111

True

## 4. Old Faithful

*Old* Faithful es un geyser en Yellowstone que erupciona cada 44-125 minutos (de acuerdo con [Wikipedia](https://es.wikipedia.org/wiki/Old_Faithful#:~:text=El%20Old%20Faithful%2C%20traducido%20al,%2C%20en%20Wyoming%2C%20Estados%20Unidos)). A las personas se les dice con frecuencia que erupciona cada una hora, pero de hecho el tiempo de espera entre erupciones es más variable. Veámoslo.

**Pregunta 1.** La primera línea de la celda de abajo asigna `tiempos_espera` a un arreglo con 272 tiempos de espera consecutivos entre erupciones, tomados de un conjunto de datos de 1938. Asigne los nombres `menor`, `mayor` y `promedio`de forma tal que la asignación `print` esté correcta. **(4 Puntos)**

In [6]:
tiempos_espera = Table.read_table('old_faithful.csv').column('waiting')

In [23]:
# BEGIN SOLUTION NO PROMPT
menor = np.min(tiempos_espera)
mayor = np.max(tiempos_espera)
promedio = np.mean(tiempos_espera)

""" # BEGIN PROMPT
menor = ...
mayor = ...
promedio = ...

""" # END PROMPT
print("Old Faithful erupciona cada", menor, "a", mayor, "minutos y cada", promedio, "minutos en promedio.")

Old Faithful erupciona cada 43 a 96 minutos y cada 70.8970588235 minutos en promedio.


In [24]:
isinstance(promedio, float) and isinstance(menor, np.int64) and isinstance(mayor, np.int64) 

True

In [26]:
promedio > 69 and promedio < 71

True

In [27]:
menor == 43

True

In [28]:
mayor == 96

True

**Pregunta 2.** Asigne `mayor_diferencia` al mayor cambio en la espera entre dos erupciones consecutivas. Por ejemplo, la tercera erupción ocurrió luego de 74 minutos y la cuarta luego de 62 minutos, así que la diferencia fue 74 - 62 = 12 minutos. **(4 Puntos)**

*Hint*: Queremos el valor absoluto del valor de la mayor diferencia.

*Nota*: `np.diff()` calcula la diferencia entre valores subsecuentes en un arreglo. Por ejemplo, llamando `np.diff()` en el arreglo `make_array(1, 8, 3, 5)`, evalúa `array([8 - 1, 3 - 8, 5 - 3])` o `array([7, -5, 2])`.

In [29]:
# BEGIN SOLUTION NO PROMPT
diferencias = np.diff(tiempos_espera)
mayor_diferencia = np.max(diferencias)

""" # BEGIN PROMPT
mayor_diferencia = ...

""" # END PROMPT
mayor_diferencia

47

In [30]:
mayor_diferencia == 47

True

In [31]:
isinstance(mayor_diferencia, np.int64)

True

**Pregunta 3.** La tabla `faithful_erupcion_nums` contiene dos columnas: `numero_erupcion`, la cual representa el número de esa erupción, y `espera`, que indica el tiempo que se tuvo que esperar luego de esa erupción. Por ejemplo, tome las primeras dos filas de la tabla:

| Número de erupción | Espera  |
|--------------------|---------|
| 1                  | 79      |
| 2                  | 54      |

Podemos leer esto como sigue: luego de la primera erupción, esperamos 79 minutos hasta que ocurrió la segunda erupción. Así, luego de la segunda erupción, esperamos 54 minutos por la tercera erupción.

Suponga que Oscar y Wendy comenzaron viendo al Old Faithful al principio de la primera erupción. Suponga que ellos observan hasta el final de la décima erupción.

Durante parte de ese tiempo estarán observando erupciones, y por el resto del tiempo estarán esperando que Old Faithful haga erupción. ¿Cuántos minutos pasarán esperando que ocurran erupciones? **(4 Puntos)**

*Hint #1:* Puede iniciar usando el método `take` en la tabla `faithful_erupcion_nums`.

*Hint #2:* `tiempo_espera_primeras_nueve` deberá ser un arreglo.

In [37]:
# Las siguientes dos líneas de código cargan la tabla faithful_erupcion_nums
faithful = Table.read_table('old_faithful.csv').drop("eruptions")
faithful_erupcion_nums = faithful.with_column("eruption number", np.arange(faithful.num_rows) + 1).select(1, 0)

In [60]:
# BEGIN SOLUTION NO PROMPT
tiempo_espera_primeras_nueve = faithful_erupcion_nums.take[:9]
tiempo_espera_primeras_nueve = tiempo_espera_primeras_nueve.column(1)
tiempo_total_espera_decima = np.sum(tiempo_espera_primeras_nueve)


""" # BEGIN PROMPT
tiempo_espera_primeras_nueve = ...
tiempo_total_espera_decima = ...

""" # END PROMPT
tiempo_total_espera_decima

633

In [61]:
633 <= tiempo_total_espera_decima <= 718

True

**Pregunta 4.** Imaginemos que su estimación del siguiente tiempo de espera siempre fue la duración del tiempo de espera anterior. Si siempre adivinara el tiempo de espera anterior, ¿qué tan grande sería, en promedio, el error al adivinar los tiempos de espera?

Por ejemplo, dado que los primeros cuatro tiempos de espera son 79, 54, 74 y 62, la diferencia promedio entre su "predicción" y el tiempo real solo para la segunda, tercera y cuarta erupciones sería: $\frac{|79-54|+ |54-74|+ |74-62|}{3} = 19$.

In [63]:
# BEGIN SOLUTION NO PROMPT
diferencias = np.diff(tiempos_espera)
error_promedio = np.sum(abs(diferencias))/(len(diferencias)-1)

""" # BEGIN PROMPT
error_promedio = ...

""" # END PROMPT
error_promedio

20.596296296296295

In [65]:
20 < error_promedio < 21

True

## 5. Tablas

**Pregunta 1.** Suponga que tiene 4 manzanas y 3 piñas. (Quizás esté usando Python para resolver un problema de álgebra del bachillerato.)Cree una tabla que contenga esta información. Esta deberá contener dos columnas: `nombre de la fruta` y `cantidad`. Asigne la nueva tabla a la variable `frutas`. **(4 Puntos)**



*Note:* Use letras minúsculas y una sola palabra para el nombre de cada fruta, por ejemplo `"manzana"`.


In [6]:
# BEGIN SOLUTION NO PROMPT
frutas = Table

""" # BEGIN PROMPT
frutas = ...
        ...
        ...

""" # END PROMPT
arreglo

AttributeError: type object 'Table' has no attribute 'foo'

In [66]:
for x in range(1,11):
    print ('{3}{0:2d}{3} {3}{1:3d}{3} {3}{2:4d}{3}'.format(x, x * x, x * x * x, '|'))

| 1| |  1| |   1|
| 2| |  4| |   8|
| 3| |  9| |  27|
| 4| | 16| |  64|
| 5| | 25| | 125|
| 6| | 36| | 216|
| 7| | 49| | 343|
| 8| | 64| | 512|
| 9| | 81| | 729|
|10| |100| |1000|


In [55]:
entregas == 4

True

**Pregunta 7.** Tiene el curso de Fundamentos de Ciencia de Datos alternativas para el examen final para aquellos que tienen inconvenientes con el horario de las clases? Asigne `examen` el número correspondiente con la mejor elección. **(3 Puntos)**

1. Sí
2. No


In [57]:
# BEGIN SOLUTION NO PROMPT
examen = 1

""" # BEGIN PROMPT
examen = ...

""" # END PROMPT
examen

1

In [58]:
examen == 1

True

**Pregunta 8:** ¿Está usted en efecto inscrito en la plataforma? Vaya a las publicaciones de este semestre y encuentre la frase secreta que publicó el instructor del curso. Asigne `secreto` a dicha frase en comillas (como una cadena de caracteres). **(4 Puntos)**

In [60]:
# BEGIN SOLUTION NO PROMPT
secreto = "El objetivo es convertir los datos en informacion y la informacion en conocimiento"

""" # BEGIN PROMPT
secreto = ...

""" # END PROMPT
secreto

'El objetivo es convertir los datos en informacion y la informacion en conocimiento'

In [62]:
x = secreto.lower()
x == "el objetivo es convertir los datos en informacion y la informacion en conocimiento"

True